# Generated by Django 5.2.5 on 2025-08-26 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="total_price",
        ),
    ]
