services:
  postgres:
    image: postgres:16
    container_name: pg_db
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    cpus: "0.50"
    mem_limit: 512m
    mem_reservation: 256m
    command: >
      postgres -c max_connections=100
              -c shared_buffers=256MB
              -c effective_cache_size=512MB
              -c maintenance_work_mem=64MB
              -c checkpoint_completion_target=0.7
              -c wal_buffers=16MB
              -c default_statistics_target=100
              -c work_mem=8MB
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d hotel_booking" ]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped

volumes:
  pgdata:
